language: ruby

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.5
  - 2.6.2

script:
  - bundle exec rspec
  - bundle exec bin/examples
  - '[[ "$(ruby -v)" < "ruby 2.4" ]] || (diff <(cat README.md) <(bin/readme))'

